print("Getting to know you!")
myName = input("What's your name? :")
myFood = input("What's your favourite food? :")
myMusic = input("What's your favourite music? :")
myPlace = input("Where do you live? :")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(myFood)
print("and you're definitely getting your groove on to.My man,")
print(myMusic)
print("living in the amazing")
print(myPlace)